services:
  db:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: trackme
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [backend]
    restart: unless-stopped

  api:
    build: ./ht-backend
    env_file: .env
    depends_on: [db]
    networks: [backend]
    restart: unless-stopped

  nginx:
    build: 
      context: ./ht-frontend
      args:
        VITE_API_BASE_URL: /api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - nginx-logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on: [api]
    networks: [backend]
    restart: unless-stopped

volumes:
  db-data:
  nginx-logs:

networks:
  backend:
