services:
  db:
    image: postgres:17-alpine
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: ./ht-backend
    env_file: .env
    depends_on: [db]
    networks: [backend]
    restart: unless-stopped

  nginx:
    image: nginx:1.28-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on: [api]
    networks: [backend]
    restart: unless-stopped

volumes:
  db-data:

networks:
  frontend:
  backend:
