name: docker-compose for .NET + Vue

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Pull latest code and build images
      run: docker compose build

    - name: Recreate containers with zero downtime
      run: docker compose up -d --remove-orphans

    - name: Cleanup old images (optional)
      run: docker image prune -f
